blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls')),
    path('', include('userapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)   

blogapp/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = "blogapp"
urlpatterns = [
    path('', views.BlogListView.as_view(), name="blog"),
    path('tag/<str:tag>/', views.BlogListView.as_view(), name="blog_tag"),
    path('post/<int:pk>-<str:slug>/', views.BlogPostView.as_view(), name="post"),
]

userapp/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = "userapp"
urlpatterns = [
    path('', views.index, name="index"),
]

blogapp/models.py
from django.db import models
from django.urls import reverse
from userapp.models import Profile
from django.utils.text import slugify

class BlogPost(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(blank=True, null=True)
    overview = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    authors = models.ManyToManyField(Profile, related_name='blogposts')
    tags = models.ManyToManyField("Tag", blank=True, related_name='blogposts')
    slug = models.SlugField(max_length=100, blank=True, unique_for_date='created')

    class Meta:
       ordering = ['-created']

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self):
        kwargs={
            'pk': self.id,
            'slug': self.slug
        }
        return reverse('blogapp:post', kwargs=kwargs)

    def save(self, *args, **kwargs):
        val = self.title
        self.slug = slugify(val, True)
        super().save(*args, **kwargs)

    @property
    def get_comments(self):
        return self.comments.all()

class Tag(models.Model):
    code = models.CharField(max_length=20)
    category = models.ManyToManyField("Category", related_name='tags')

    def __str__(self) -> str:
        return self.code

class Category(models.Model):
    code = models.CharField(max_length=20)

    def __str__(self) -> str:
        return self.code

class Comment(models.Model):
    post = models.ForeignKey(BlogPost, null=True, blank=True, on_delete=models.CASCADE, related_name='comments')
    parent = models.ForeignKey('self', null=True, blank=True, on_delete = models.CASCADE)
    author = models.CharField(max_length=50)
    email = models.EmailField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    content = models.TextField()

    class Meta:
        ordering = ('created',)

    def __str__(self) -> str:
        return f'Comment by {self.author}, created on {self.created}'    

    def get_comments(self):
        return Comment.objects.filter(parent=self)

userapp/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.ImageField()

    def __str__(self) -> str:
        return str(self.user)

blogapp/forms.py
from typing import Text
from django.forms import ModelForm, Textarea
from django.forms.widgets import TextInput, EmailInput
from .models import Comment

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['author', 'email', 'content']
        
        comment_field = {'class': 'form-control my-2 comment-field'}
        widgets = {
            'author': TextInput(attrs=comment_field),
            'email': EmailInput(attrs=comment_field),
            'content': Textarea(attrs={'rows': 5, 'class': 'form-control my-2'}),
        }

blogapp/views.py
from blogapp.models import BlogPost
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import generic
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import CommentForm
from .models import Comment
from .utils import tags_count, similar_posts

class BlogListView(generic.ListView):
    model = BlogPost
    template_name = "blogapp/blog.html"
    paginate_by = 5
    tag = None

    def get_context_data(self, **kwargs):
        context = super(BlogListView, self).get_context_data(**kwargs)
        context['tags_count'] = tags_count()      
        if self.tag != None:
            context['tag'] = self.tag
        return context

    def get_queryset(self):
        self.tag = self.kwargs.get('tag', None)
        if self.tag != None:
            return BlogPost.objects.filter(tags__code__in=[self.tag])[:5]   
        return BlogPost.objects.all()[:5]

class BlogPostView(generic.DetailView):
    model = BlogPost 
    template_name = "blogapp/post.html"  

    def get_context_data(self, **kwargs):
        self.object = self.get_object()
        context = super(BlogPostView, self).get_context_data(**kwargs)
        context['comment_form'] = CommentForm()
        context['similar_posts'] = similar_posts(self.object.id)
        return context
    
    def post(self, request, *args, **kwargs):
        # Process added comments
        self.object = self.get_object()
        if (request.method == "POST") and ('comment_form' in request.POST):
            # Saving added comment
            cform = CommentForm(request.POST)
            if cform.is_valid():
                comment = Comment(
                    post=self.object, 
                    author=cform.cleaned_data["author"],
                    email=cform.cleaned_data["email"], 
                    content=cform.cleaned_data["content"]
                )
                comment.save()
                kwargs={
                    'pk': kwargs['pk'],
                    'slug': kwargs['slug'],
                }
                return redirect(reverse("blogapp:post", kwargs=kwargs))
        return render(request, self.template_name, self.get_context_data())

userapp/views.py
from django.shortcuts import render

def index(request):
    pass

blogapp/templates/blogapp/blog.html
{% extends "blogapp/layout.html" %}
{% load static %}

{% block main %}
<main class="container">
<div class="row blog-font mt-3">
    <div class="col-md-8">
      {% for obj in object_list %}
      <article class="blog-post">
        <div class="row">
          <a href="{{ obj.get_absolute_url }}">
          <div class="col d-flex flex-column position-static">
            <a class="plain-a" href="{{ obj.get_absolute_url }}"><h4>{{ obj.title }}</h4></a>
            {% include "blogapp/blogpost_header.html" with blogpost=obj %}
            <p>{{ obj.overview }}</p>
          </div>
          <div class="col-auto d-none d-lg-block">
            <a class="plain-a" href="{{ obj.get_absolute_url }}"><img src="{{ obj.image.url }}" class="img-thumbnail" width="200" height="200"></a>
          </div>
        </div>  
      </article>    
      {% empty %}
        <div><h4>There are no posts yet.</h4></div>
      {% endfor %}

      {% block pagination %}
      {% if is_paginated %}
      <nav aria-label="Pagination">  
        <ul class="pagination pagination-template d-flex justify-content-center">
          {% if page_obj.has_previous %}                
          <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link">{{ page_obj.previous_page_number }}</a></li>
          {% endif %}
          <li class="page-item active"><a href="?page={{ page_obj.number }}" class="page-link">{{ page_obj.number }}</a></li>
          {% if page_obj.has_next %}
          <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link">{{ page_obj.next_page_number }}</a></li>
          {% endif %}
        </ul>
      </nav>     
      {% endif %}
      {% endblock %}
    </div>

    <div class="col-md-4 bg-light rounded">      
      <div class="p-4 mb-3">
        {% if tag %}
        <div>Showing posts with tag: <b>{{ tag }}</b></div>
        {% endif %}
        <div><h5><a class="plain-a" href="{% url 'blogapp:blog' %}">Show all posts</a></h5></div>
        <h5 class="mt-4">Tags</h5>
        {% for tag in tags_count %}
        <div class="item d-flex justify-content-between">
          <a href="{% url 'blogapp:blog_tag' tag.code %}">{{ tag.code }}</a><span>{{ tag.posts_count }}</span>
        </div>
        {% endfor %}
      </div>
    </div>
</div><!-- /.row -->
</main>
{% endblock %}

blogapp/templates/blogapp/blogpost_header.html
<p class="blog-post-meta">{{ blogpost.created }} by 
    {% for author in blogpost.authors.all %}<a href="">{{ author.user }}</a>&nbsp;{% endfor %}
    <br>
    <span class="category">
    {% for tag in blogpost.tags.all %} 
    <a href="{% url 'blogapp:blog_tag' tag %}">{{ tag }}</a>
    {% endfor %}
    </span>   
</p>

blogapp/templates/blogapp/layout.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    
    <!-- Blog resources -->
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
    <link href="{% static 'blogapp/blog.css' %}" rel="stylesheet">
    <script src="{% static 'blogapp/blog.js' %}"></script>
    <!-- Blog resources -->

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>

<main class="container">
  {% block main %}
  {% endblock %}  
</main>

<footer></footer>
    <!-- jQuery, Popper and Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="https://code.jquery.com/jquery-3.6.0.slim.min.js"><\/script>')</script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
  </body>
</html>

blogapp/templates/blogapp/post.html
{% extends "blogapp/layout.html" %}
{% load static %}

{% block main %}
<main class="container">
<div class="row mt-3">
    <div class="col-md-8">
      <article class="blog-post">
        <div class="row">
          <div class="col d-flex flex-column position-static">
            <h3>{{ blogpost.title }}</h3>
            {% include "blogapp/blogpost_header.html" with blogpost=blogpost %}
          </div> 
          <div class="col-auto d-none d-lg-block">
            <img src="{{ blogpost.image.url }}" class="img-thumbnail" width="200" height="200">
          </div>
        </div>  
        <p class="mt-2">{{ blogpost.content }}</p>
        
        <div class="mt-4 comment-font">
          <div class="p-3">
            <h6>Comments ({{ blogpost.get_comments.count }})</h6>
          </div>
          {% for comment in blogpost.get_comments %} 
          <div class="d-flex flex-row p-3"> 
            <img src="{% static 'blogapp/src/awesome192.png' %}" width="50" height="50" class="rounded-circle">
            <div class="w-100 ms-3">
                <div class="d-flex justify-content-between align-items-center">
                    <div class="d-flex flex-row align-items-center">
                      <span class="fw-bolder">{{ comment.author }}</span> 
                    </div> 
                    <small>{{ comment.created }}</small>
                </div>
                <p class="text-justify comment-text mb-0">{{ comment.content }}</p>
                <div class="d-flex flex-row user-feed"> 
                  <span class="ml-3 fw-lighter"><i class="fa fa-comments-o mr-2"></i>Reply</span> 
                </div>
            </div>
          </div>
          {% endfor %}

          <div class="p-3">
            <form method="post">
              {% csrf_token %}
              {{comment_form }}
              <input class="btn greenbg comment-font" name="comment_form" type="submit" value="Comment">
            </form>
          </div>
        </div>
      </article>    
    </div>
    <div class="col-md-4 bg-light">
      <div class="p-4 mb-3 rounded">          
        <div class="mb-3"><h5><a class="plain-a" href="{% url 'blogapp:blog' %}">Back to posts</a></h5></div>
        {% if similar_posts %}
          <div>Similar posts:</div>
          {% for post in similar_posts %}
          <div><a href="{{ post.get_absolute_url }}">{{ post }}</a></div>
          {% endfor %}
        {% endif %} 
      </div>
    </div>
</div><!-- /.row -->
</main>
{% endblock %}